apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service-2
  namespace: kube-honduras
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2 #$1 cuts hostname, $2 cuts (abc.com/to_be_cut/some ==> abc.com/some)
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.org/proxy-connect-timeout: "60s"
    nginx.org/proxy-read-timeout: "60s"
    nginx.org/client-max-body-size: "100m"    
spec:
  tls:
    - hosts:
        - {{SIPAC_HOSTNAME}}
      secretName: {{SIPAC_HOSTNAME}}-secret-name
  rules:
    - host: {{SIPAC_HOSTNAME}}
      http:
        paths:        
        - path: /ws(/|$)(.*)
          backend:
            serviceName: websocket
            servicePort: 8082

        - path: /backend(/|$)(.*) # {{SIPAC_HOSTNAME}}/backend
          backend:
            serviceName: ms-security
            servicePort: 8090

        - path: /dashboard(/|$)(.*)
          backend:
            serviceName: kibana-honduras-kb-http
            servicePort: 5601